# Application Name
spring.application.name=whatsapp-crm

# Server Configuration
server.port=8080

# Jackson Configuration
spring.jackson.time-zone=UTC

# Actuator Configuration
management.endpoints.web.exposure.include=health,info

# WhatsApp Provider Configuration
whatsapp.providers.meta.apiBaseUrl=https://graph.facebook.com/v22.0
whatsapp.providers.meta.phoneNumberId=765240973349328
whatsapp.providers.meta.accessToken=EAAr9XIzCtQ8BQNymVXirYlixxpbGMVEwKPl23Xu7XtFXSeQZCZCwcOuZBj3y1kx4QBUO9YZBZA2y6r7UXRxFhfMl4bhUqebDLDLRdYAZBVI5VA6GpUDfZBaTSOiKLZCbKntdS6qz8FuZBoJR35IzHDXhkLlW1JCP9NVAe1hCwfNe4ehiZBZCRNVZB2JOqmk7GeETFDaL0CobmkC2ZBDDpWuCHYHzz9AZBN4f8oEPpPIV91d9d35MVdr2AF7gy3cai5zDGbuZCTjeZCHjnQmGazSVgCQmp1pAzSG244aNcdPS8hvF1kUZD
whatsapp.throttle.messagesPerSecond=5
whatsapp.webhook.verify-token=varta_webhook_secret
whatsapp.webhook.auth-token=varta_api_secret

# Security JWT Configuration
security.jwt.secret=THIS_IS_A_MUCH_LONGER_SUPER_SECRET_KEY_FOR_JWT_THAT_SHOULD_BE_AT_LEAST_256_BITS_LONG_SO_IT_WORKS_CORRECTLY_WITH_HMAC_SHA256
security.jwt.expirationSeconds=3600

# Active Profile (default to local, can be overridden)
spring.profiles.active=local

## Local Profile Configuration
#spring.config.activate.on-profile=local

# AWS Profile Configuration
#psql 'postgresql://neondb_owner:npg_3jnpsCLMxDN0@ep-purple-moon-a1gss1eb-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
spring.datasource.url=jdbc:postgresql://ep-green-darkness-a1y31vkp-pooler.ap-southeast-1.aws.neon.tech/VartaAi?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gV1kO5zUimSt
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.jdbc.time_zone=IST
spring.datasource.database=VartaAI
